### ISSUE TITLE
On priorities

### ISSUE THREAD

**Issue by felipebn** [blmayer/blog#1]
I read this and thought about it and wanted to comment for some reason.

What about if priorities are not in a scale from 0-Inf but a stack ? So if some comes in and it's more important than what is there already it's at index 0... just a thought :) 

https://github.com/blmayer/blog/blob/bb92929555450a45577500fb24e17c51d22cd071/posts/04-prioridade-zero-pt-br.html.tpl#L12

**Comment by blmayer** [comment]
Hi,

Thanks for dropping a line here.

Interesting thought, maybe there is a data structure that's perfect for it. I'm not sure about stacks, as they are LIFOs and usually APIs only let you pop and insert at the top. So if a smaller priority comes you must put it at top, which is weird, but for new top priorities it works.
